program: test_heuristic_from_config.py
method: grid
#method: bayes
metric:
  goal: maximize
  name: analyzer/result_by_team_0/.total_score
parameters:
        
    #epoch_loop.rllib_config.env_config.reward_function_kwargs.fail_reward_factor:
        #values: [1, 2, 4, 8]

    env_loop.teams_config.deep_nmmo.envs.team_based_env.teams.custom_team.CustomTeam.paths_to_agents_cls:
        values:
            - ['neurips2022nmmo.scripted.baselines.Fisher',
               'neurips2022nmmo.scripted.baselines.Herbalist',
               'neurips2022nmmo.scripted.baselines.Prospector',
               'neurips2022nmmo.scripted.baselines.Carver',
               'neurips2022nmmo.scripted.baselines.Alchemist',
               'neurips2022nmmo.scripted.baselines.Melee',
               'neurips2022nmmo.scripted.baselines.Range',
               'neurips2022nmmo.scripted.baselines.Mage']

            - ['neurips2022nmmo.scripted.baselines.Fisher',
               'neurips2022nmmo.scripted.baselines.Herbalist',
               'neurips2022nmmo.scripted.baselines.Melee',
               'neurips2022nmmo.scripted.baselines.Range',
               'neurips2022nmmo.scripted.baselines.Alchemist',
               'neurips2022nmmo.scripted.baselines.Melee',
               'neurips2022nmmo.scripted.baselines.Range',
               'neurips2022nmmo.scripted.baselines.Mage']

    #env_loop.teams_config:
        #values:
            #[
                #{
                #deep_nmmo.envs.team_based_env.teams.custom_team.CustomTeam:
                    #team_id: 'Custom'
                    #paths_to_agents_cls:
                        #- 'neurips2022nmmo.scripted.baselines.Fisher'
                        #- 'neurips2022nmmo.scripted.baselines.Herbalist'
                        #- 'neurips2022nmmo.scripted.baselines.Prospector'
                        #- 'neurips2022nmmo.scripted.baselines.Carver'
                        #- 'neurips2022nmmo.scripted.baselines.Alchemist'
                        #- 'neurips2022nmmo.scripted.baselines.Melee'
                        #- 'neurips2022nmmo.scripted.baselines.Range'
                        #- 'neurips2022nmmo.scripted.baselines.Mage'

                #neurips2022nmmo.scripted.CombatTeam: 
                    #team_id: 'Combat'

                #neurips2022nmmo.scripted.MixtureTeam:
                    #team_id: 'Mixture'
              #}
            #]




command:
  - ${env}
  - python
  - ${program}
  - --config-path=configs
  - ${args_no_hyphens}
