experiment:
    name: 'neurips2022nmmo'
    seed: 0
    path_to_save: '/scratch/datasets/nmmo/sims/'
    save_dir: null # placeholder, will be updated
    num_epochs: 1

wandb:
    init:
        project: nmmo
        entity: ong 

env_loop:
    _target_: deep_nmmo.envs.team_based_env.loops.env_loop.EnvLoop

    path_to_env_cls: 'neurips2022nmmo.TeamBasedEnv'

    path_to_env_config_cls: 'neurips2022nmmo.CompetitionConfig'
    #path_to_env_config_cls: 'deep_nmmo.envs.team_based_env.env_configs.custom_competition_config.CustomCompetitionConfig'

    teams_config:
        deep_nmmo.envs.team_based_env.teams.custom_team.CustomTeam:
            team_id: 'Custom'
            paths_to_agents_cls:
                - 'neurips2022nmmo.scripted.baselines.Fisher'
                - 'neurips2022nmmo.scripted.baselines.Herbalist'
                - 'neurips2022nmmo.scripted.baselines.Prospector'
                - 'neurips2022nmmo.scripted.baselines.Carver'
                - 'neurips2022nmmo.scripted.baselines.Alchemist'
                - 'neurips2022nmmo.scripted.baselines.Melee'
                - 'neurips2022nmmo.scripted.baselines.Range'
                - 'neurips2022nmmo.scripted.baselines.Mage'

        neurips2022nmmo.scripted.CombatTeam: 
            team_id: 'Combat'

        neurips2022nmmo.scripted.MixtureTeam:
            team_id: 'Mixture'
        

    teams_copies:
        ## CompetitionConfig
        #- 5
        #- 11
        
        # CompetitionConfig
        - 1
        - 5
        - 10
        
        ## CustomCompetitionConfig
        #- 1
        #- 1

    env_config_kwargs: null
    parallel: true


